<a href="https://colab.research.google.com/github/YeonKang/Tensorflow-with-Colab/blob/master/Extra__tf_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import traceback
import contextlib

#Helper function for error output
@contextlib.contextmanager
def assert_raises(error_class):
  try:
    yield
  except error_class as e:
    print('Throwing the expected exception \n  {}:'.format(error_class))
    traceback.print_exc(limit=2)
  except Exception as e:
    raise e
  else:
    raise Exception('Expected {}, but no error occurred'.format(
        error_class))

**calcultate gradient descent with tf.function**

In [2]:
@tf.function
def add(a, b):
  return a + b

add(tf.ones([2, 2]), tf.ones([2, 2]))  #  [[2., 2.], [2., 2.]]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [3]:
v = tf.Variable(1.0)
with tf.GradientTape() as tape:
  result = add(v, 1.0)
tape.gradient(result, v)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

**use tf.function in another function**

In [4]:
@tf.function
def dense_layer(x, w, b):
  return add(tf.matmul(x, w), b)

In [5]:
dense_layer(tf.ones([3, 2]), tf.ones([2, 2]), tf.ones([2]))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.],
       [3., 3.]], dtype=float32)>

**Compare tf.function and eager execution for a large amount of computation**

In [6]:
import timeit
conv_layer = tf.keras.layers.Conv2D(100, 3)

@tf.function
def conv_fn(image):
  return conv_layer(image)

image = tf.zeros([1, 200, 200, 100])

conv_layer(image); conv_fn(image)
print("tf.function convolution:", timeit.timeit(lambda: conv_fn(image), number=10))
print("eager execution convolution:", timeit.timeit(lambda: conv_layer(image), number=10))
print("There is no significant difference in the speed of the convolution operation.")

tf.function convolution: 0.9859724309999933
eager execution convolution: 1.0078036670000188
There is no significant difference in the speed of the convolution operation.
